### ISSUE TITLE
Descriptions with the same type should go to the single narrative

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream-v201-migration#1]
V201 doesn't allow multiple descriptions with the same type - say Objectives. There are organisations with multiple description with the same type and they have been mapped to multiple narratives. They should all have been concatenated and moved to single narrative only for the given language.

**Comment by anjesh** [comment]
fixed and re-migrated. @iatisupport

**Comment by iatisupport** [comment]
Hi Anjesh I don't think this is still working correctly yet. Flora and Fauna have valid multiple descriptions in two different languages but they have been incorrectly amalgamated. Please could you invetigate?

**Comment by anjesh** [comment]
Hi Wendy, The case for Flora and Fauna has been corrected now.

**Comment by iatisupport** [comment]
Hi Anjesh, I've just had a look at this on the V2.01 site and I think that unfortunately it is still not quite correct. I think it needs to be one (not two separate) description field but with two narrative fields - one in english and the other in Spanish. Hope that makes sense

**Comment by anjesh** [comment]
This is also fixed. Please verify.

**Comment by iatisupport** [comment]
Yes all looks fine now thanks

**Comment by danmackenzie** [comment]
Hi

Sorry to bring this one up for the dark again, but on the recent activities-errors-csv sent through I've found an organisation that is creating an error because they have two descriptions of the same type, but in a different language.

Org: Railway Children

Activity: GB-CHC-1058991-TAN01

Issue: Two descriptions with Type: General. But they are in different languages. Should this still be considered an error?

http://www.aidstream.org/activity/view-activity-info/?activity_id=377

Thanks,

Daniel

**Comment by iatisupport** [comment]
Thanks Daniel - interesting one. I think in this case this activity should be migrated to V2.01 as a single description field of type general but with two narrative fields - one in each language. I've had a look in http://v201.aidstream.org/ and this looks like what has happened so I think we are probably okay on this one. Cheers
