### ISSUE TITLE
Org ID changed in Settings and Activity, but not in Organisation File

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream-v201-migration#23]
Org ID changed in Settings and Activity, but not in Organisation File - United Mission to Nepal (SN 477). They have a new Org ID - XI-IATI-1002 which replaces their old one which starts NP-SW... They have changed it in the Settings and Activity screens, but the change hasn't been applied automatically to the Organisation File screen, and there seems no way of manually changing it. Any idea of how to fix?

![united mission to nepal setting with new org id](https://cloud.githubusercontent.com/assets/8158574/10136810/4a0582a2-65ee-11e5-9ed7-f8d8020dd043.png)
![united mission to nepal org file old org id](https://cloud.githubusercontent.com/assets/8158574/10136811/4d5f0450-65ee-11e5-9551-49e890434105.png)

**Comment by anjesh** [comment]
There has been a little bug in the system after we changed the message when the user updates the reporting-org-id. It has been fixed now in aidstream.org.

**Comment by SJ-bond** [comment]
Hello, thanks for fixing this. I still can't get the org id to change in the organisation data file in United Mission to Nepal (S.N. 477) - is there a way that you can do it manually please?

**Comment by anjesh** [comment]
It's fixed in org-file. Please verify.
